/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioWaveform: typeof import('./src/components/AudioWaveform.vue')['default']
    BarContainer: typeof import('./src/components/Container/BarContainer.vue')['default']
    ChatWindow: typeof import('./src/components/Chat/ChatWindow.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LineContainer: typeof import('./src/components/Container/LineContainer.vue')['default']
    MaskLayer: typeof import('./src/components/MaskLayer.vue')['default']
    PieContainer: typeof import('./src/components/Container/PieContainer.vue')['default']
    PipelineAccessSettings: typeof import('./src/components/Pipeline/PipelineAccessSettings.vue')['default']
    PipelineHeader: typeof import('./src/components/Pipeline/PipelineHeader.vue')['default']
    PipelineMainData: typeof import('./src/components/Pipeline/PipelineMainData.vue')['default']
    PipelineMainTask: typeof import('./src/components/Pipeline/PipelineMainTask.vue')['default']
    RadarContainer: typeof import('./src/components/Container/RadarContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingChart: typeof import('./src/components/Pipeline/SettingChart.vue')['default']
    SettingDataSource: typeof import('./src/components/Pipeline/SettingDataSource.vue')['default']
    SettingPreprocess: typeof import('./src/components/Pipeline/SettingPreprocess.vue')['default']
    SettingStatement: typeof import('./src/components/Pipeline/SettingStatement.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Statement: typeof import('./src/components/Pipeline/Statement.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
